import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={'mx-auto w-11/12'}>
          <div className={'h-24 w-full border-b-white border-b-2'}></div>
          <div className={'pt-16'}>{children}</div>
        </div>
      </body>
    </html>
  )
}
